# Track Chrome stable.
# https://omahaproxy.appspot.com/
# This formula is auto-generated by load_deps.py script. Do not edit it manually.
class V8 < Formula
  desc "Google's JavaScript engine"
  homepage "https://code.google.com/p/v8/"
  url "https://github.com/v8/v8/archive/5.6.222.tar.gz"
  sha256 "574592cb40d509cb490ae0f4550c5bbde2442d423adaaa9fc20db9b3d3affab0"
  head "https://github.com/v8/v8.git"

  bottle do
    cellar :any
  end

  option "with-readline", "Use readline instead of libedit"

  # not building on Snow Leopard:
  # https://github.com/Homebrew/homebrew/issues/21426
  depends_on :macos => :lion

  depends_on :python => :build # gyp doesn't run under 2.6 or lower
  depends_on "readline" => :optional
  depends_on "icu4c" => :recommended

  needs :cxx11

  # Update from "DEPS" file in tarball.

  # resources definition, do not edit, autogenerated

  resource "mozilla-tests" do
    url "https://chromium.googlesource.com/v8/deps/third_party/mozilla-tests.git",
    :revision => "f6c578a10ea707b1a8ab0b88943fe5115ce2b9be"
  end

  resource "buildtools" do
    url "https://chromium.googlesource.com/chromium/buildtools.git",
    :revision => "39b1db2ab4aa4b2ccaa263c29bdf63e7c1ee28aa"
  end

  resource "ecmascript_simd" do
    url "https://chromium.googlesource.com/external/github.com/tc39/ecmascript_simd.git",
    :revision => "baf493985cb9ea7cdbd0d68704860a8156de9556"
  end

  resource "googlemock" do
    url "https://chromium.googlesource.com/external/googlemock.git",
    :revision => "0421b6f358139f02e102c9c332ce19a33faf75be"
  end

  resource "clang" do
    url "https://chromium.googlesource.com/chromium/src/tools/clang.git",
    :revision => "75350a858c51ad69e2aae051a8727534542da29f"
  end

  resource "markupsafe" do
    url "https://chromium.googlesource.com/chromium/src/third_party/markupsafe.git",
    :revision => "484a5661041cac13bfc688a26ec5434b05d18961"
  end

  resource "googletest" do
    url "https://chromium.googlesource.com/external/github.com/google/googletest.git",
    :revision => "6f8a66431cb592dad629028a50b3dd418a408c87"
  end

  resource "jinja2" do
    url "https://chromium.googlesource.com/chromium/src/third_party/jinja2.git",
    :revision => "b61a2c009a579593a259c1b300e0ad02bf48fd78"
  end

  resource "build" do
    url "https://chromium.googlesource.com/chromium/src/build.git",
    :revision => "a3b623a6eff6dc9d58a03251ae22bccf92f67cb2"
  end

  resource "benchmarks" do
    url "https://chromium.googlesource.com/v8/deps/third_party/benchmarks.git",
    :revision => "05d7188267b4560491ff9155c5ee13e207ecd65f"
  end

  resource "gyp" do
    url "https://chromium.googlesource.com/external/gyp.git",
    :revision => "e7079f0e0e14108ab0dba58728ff219637458563"
  end

  resource "test262" do
    url "https://chromium.googlesource.com/external/github.com/tc39/test262.git",
    :revision => "fb61ab44eb1bbc2699d714fc00e33af2a19411ce"
  end

  resource "instrumented_libraries" do
    url "https://chromium.googlesource.com/chromium/src/third_party/instrumented_libraries.git",
    :revision => "45f5814b1543e41ea0be54c771e3840ea52cca4a"
  end

  resource "swarming" do
    url "https://chromium.googlesource.com/external/swarming.client.git",
    :revision => "380e32662312eb107f06fcba6409b0409f8fef72"
  end

  resource "test262-harness-py" do
    url "https://chromium.googlesource.com/external/github.com/test262-utils/test262-harness-py.git",
    :revision => "cbd968f54f7a95c6556d53ba852292a4c49d11d8"
  end

  resource "icu" do
    url "https://chromium.googlesource.com/chromium/deps/icu.git",
    :revision => "b0bd3ee50bc2e768d7a17cbc60d87f517f024dbe"
  end

  resource "common" do
    url "https://chromium.googlesource.com/chromium/src/base/trace_event/common.git",
    :revision => "06294c8a4a6f744ef284cd63cfe54dbf61eea290"
  end

  def install
    # Bully GYP into correctly linking with c++11
    ENV.cxx11
    ENV["GYP_DEFINES"] = "clang=1 mac_deployment_target=#{MacOS.version}"
    # https://code.google.com/p/v8/issues/detail?id=4511#c3
    ENV.append "GYP_DEFINES", "v8_use_external_startup_data=0"

    if build.with? "icu4c"
      ENV.append "GYP_DEFINES", "use_system_icu=1"
      i18nsupport = "i18nsupport=on"
    else
      i18nsupport = "i18nsupport=off"
    end

    # fix up libv8.dylib install_name
    # https://github.com/Homebrew/homebrew/issues/36571
    # https://code.google.com/p/v8/issues/detail?id=3871
    inreplace "src/v8.gyp",
              "'OTHER_LDFLAGS': ['-dynamiclib', '-all_load']",
              "\\0, 'DYLIB_INSTALL_NAME_BASE': '#{opt_lib}'"

    # resources installation, do not edit, autogenerated
    (buildpath/"test/mozilla/data").install resource("mozilla-tests")
    (buildpath/"buildtools").install resource("buildtools")
    (buildpath/"test/simdjs/data").install resource("ecmascript_simd")
    (buildpath/"testing/gmock").install resource("googlemock")
    (buildpath/"tools/clang").install resource("clang")
    (buildpath/"third_party/markupsafe").install resource("markupsafe")
    (buildpath/"testing/gtest").install resource("googletest")
    (buildpath/"third_party/jinja2").install resource("jinja2")
    (buildpath/"build").install resource("build")
    (buildpath/"test/benchmarks/data").install resource("benchmarks")
    (buildpath/"tools/gyp").install resource("gyp")
    (buildpath/"test/test262/data").install resource("test262")
    (buildpath/"third_party/instrumented_libraries").install resource("instrumented_libraries")
    (buildpath/"tools/swarming_client").install resource("swarming")
    (buildpath/"test/test262/harness").install resource("test262-harness-py")
    (buildpath/"third_party/icu").install resource("icu")
    (buildpath/"base/trace_event/common").install resource("common")

    system "make", "native", "library=shared", "snapshot=on",
                   "console=readline", i18nsupport,
                   "strictaliasing=off"

    include.install Dir["include/*"]

    cd "out/native" do
      rm ["libgmock.a", "libgtest.a"]
      lib.install Dir["lib*"]
      bin.install "d8", "mksnapshot", "process", "v8_shell" => "v8"
    end
  end

  test do
    assert_equal "Hello World!", pipe_output("#{bin}/v8 -e 'print(\"Hello World!\")'").chomp
  end
end
